lookup_excluded_programs <- c("MS", "SAA", "DOS")

lookup_discipline_lookup <- tibble::tribble(
  ~dept, ~discpln,
  "ACC", "Business",
  "ANT", "Social Sciences",
  "ART", "Arts",
  "BIO", "Natural Sciences",
  "CHM", "Natural Sciences",
  "CS", "Mathematical & Computational Sciences",
  "CST", "Social Sciences",
  "DES", "Education",
  "ECO", "Business",
  "ENG", "Humanities",
  "ESS", "Human Performance & Applied Health",
  "FIN", "Business",
  "GCL", "Humanities",
  "GEO", "Environmental Science",
  "HIS", "Humanities",
  "HP", "Health Sciences",
  "IS", "Business",
  "MGT", "Business",
  "MIC", "Natural Sciences",
  "MKT", "Business",
  "MTH", "Mathematical & Computational Sciences",
  "MUS", "Arts",
  "PH", "Health Sciences",
  "PHL", "Humanities",
  "PHY", "Natural Sciences",
  "POL", "Social Sciences",
  "PROV", "University",
  "PSY", "Social Sciences",
  "RGS", "Social Sciences",
  "RMRT", "Human Performance & Applied Health",
  "SOC", "Social Sciences",
  "THA", "Arts",
)

lookup_subject_lookup <- tibble::tribble(
  ~subject, ~dept,
  "ACC", "ACC",
  "ANT", "ANT",
  "ARC", "ANT",
  "ART", "ART",
  "ATS", "ESS",
  "BIO", "BIO",
  "BLAW", "ACC",
  "CHE", "PH",
  "CHI", "GCL",
  "CHM", "CHM",
  "CLI", "MIC",
  "CPE", "CS",
  "CRIM", "SOC",
  "CS", "CS",
  "CST", "CST",
  "CT", "CS",
  "CYB", "CST",
  "CYC", "PSY",
  "DMK", "MKT",
  "DMS", "HP",
  "DOS", "HP",
  "DS", "MTH",
  "DSC", "MTH",
  "ECE", "DES",
  "ECO", "ECO",
  "EDS", "DES",
  "EDU", "DES",
  "EFN", "DES",
  "ENG", "ENG",
  "ENV", "PHL",
  "ESS", "ESS",
  "FIN", "FIN",
  "FNS", "BIO",
  "FNT", "CS",
  "FRE", "GCL",
  "FYS", "PROV",
  "GCL", "GCL",
  "GEO", "GEO",
  "GER", "GCL",
  "HCA", "PH",
  "HCK", "GCL",
  "HIS", "HIS",
  "HMG", "GCL",
  "HP", "HP",
  "HPR", "ESS",
  "INS", "HIS",
  "IS", "IS",
  "ITM", "IS",
  "JPN", "GCL",
  "LS", "PROV",
  "MGT", "MGT",
  "MIC", "MIC",
  "MIND", "RMRT",
  "MKT", "MKT",
  "MS", "MS",
  "MTH", "MTH",
  "MUA", "MUS",
  "MUS", "MUS",
  "NEU", "PSY",
  "NMT", "HP",
  "NUT", "BIO",
  "OT", "HP",
  "PAS", "HP",
  "PH", "PH",
  "PHL", "PHL",
  "PHY", "PHY",
  "POL", "POL",
  "PSY", "PSY",
  "PTS", "HP",
  "PUB", "POL",
  "RAD", "HP",
  "RDG", "DES",
  "REC", "RMRT",
  "RGS", "RGS",
  "RT", "HP",
  "RTH", "RMRT",
  "RUS", "GCL",
  "SAA", "SAA",
  "SOC", "SOC",
  "SPA", "GCL",
  "SPE", "DES",
  "SPY", "PSY",
  "STAT", "MTH",
  "THA", "THA",
  "TSL", "DES",
  "UWL", "PROV",
)
